### ISSUE TITLE
Localhost:3000 and 80 can't be reached

### ISSUE THREAD

**Issue by Godtide** [Alethio/memento#13]
I got Memento to work in the terminal with ganache on port: 8545, but can't connect with the dashboard on localhost:3000
The localhost:80 logs error can't find config.json

**Comment by Godtide** [comment]
in the terminal: only the **reset** command gives the desired response, **run, migrate, queue** command don't

**Comment by Godtide** [comment]
I think, there's no web build service in the compose file

**Comment by kwix** [comment]
Hey @Godtide ! 

The [docker-compose file ](https://github.com/Alethio/memento/blob/master/docker-compose-explorer.yml) for running memento with lite explorer are exposing the ports `3000`, `3001` from `memento` and `80` from `memento-lite-explorer`. 

Did you make any changes to the docker-compose file? Could you share it with us so we can have a better chance of helping you out?

**Comment by Godtide** [comment]
Thanks @kwix 
This is what I have https://github.com/Godtide/mementoLocale following guidelines from https://alethio.gitbook.io/memento/running-memento/bundled-with-lite-explorer

This response from **docker ps**
![memento1](https://user-images.githubusercontent.com/26319257/77697933-0b232000-6fb0-11ea-8a9e-6533dd5d0599.PNG)

But on localhost:3000
![memento2](https://user-images.githubusercontent.com/26319257/77698454-ebd8c280-6fb0-11ea-917f-ee71d37fc8e3.PNG)

**Comment by kwix** [comment]
Could you give us some more details about the operating system you're using and how you're running memento? 
I know this might sound dumb, but I really have to make sure, are you trying to access `http://127.0.0.1:3000` on the same machine? Is there any virtual machine of some kind or anything like that in your setup?

**Comment by Godtide** [comment]
I'm using a VM instance of Ubuntu 18.04

**Comment by kwix** [comment]
Are you trying to access `http://127.0.0.1:3000` inside the VM or from your host machine? 

None of the exported ports will work outside the VM unless you find a way to forward them between the host and the VM.

**Comment by kwix** [comment]
I will close this since it there is no new reply for a few weeks now. Feel free to open a new issue if you've got other problems.

**Comment by SalahAdDin** [comment]
I have the same problem now, could you solve it?

**Comment by dineshtiwari69** [comment]
Everyone looking forward to fix the issue , you can check the log and detect the problem. 

For me it was the incorrect RPC URL.
docker-compose logs --tail=10 memento
