### ISSUE TITLE
Connecting memento to besu network with ibft2 seems to fail

### ISSUE THREAD

**Issue by ArvsIndrarys** [Alethio/memento#14]
Using the docker setup with :
- alethio/memento:v1.1.4
- redis:5.0.5-alpine
- postgres:11.5-alpine
- alethio/ethereum-lite-explorer:v1.0.0-beta.8
- hyperledger/besu:1.4

Gives the following error message in memento :
```
time="2020-04-20T14:03:31Z" level=info msg="[eth] setting up best block polling"
time="2020-04-20T14:03:31Z" level=error msg="[eth] protocol not recognized, use http(s) or ws(s)"
```

Moreover, I don't think the problem comes with the RPC url (http://x.x.x.x:8545) because it worked with the alethio lite explorer, when used without memento.
I tried not to show the ws port with `ws: ""` and after `ws: "ws://x.x.x.x:8546"` as the webservices are not exposed on the server.

Do memento work with besu 1.4 for a ibft2 network? Or do you think it is due to misconfiguration?

If needed, I can share my config files in a gist

**Comment by kwix** [comment]
Hello! 

From the logs you posted it looks like the  url for eth client connection is wrong.
If you could share the config you used, I might be able to help.

**Comment by ArvsIndrarys** [comment]
I am trying to debug it a little with a local besu node.
The real node I want to connect to is on a distant server with the websocket port closed. I think it lay be due to that.
I'll keep you in touch !

**Comment by ArvsIndrarys** [comment]
The gist is located at : 
https://gist.github.com/ArvsIndrarys/d842bb92817d93c7488d9911c4a34d9a

Even locally, ( connexion to besu node as http://node:8545) I have the problem.

**Comment by ArvsIndrarys** [comment]
From the explorer : 
```
/app # curl node0:8545 -v
*   Trying 172.18.0.6:8545...
* TCP_NODELAY set
* Connected to node0 (172.18.0.6) port 8545 (#0)
> GET / HTTP/1.1
> Host: node0:8545
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< content-length: 0
< 
* Connection #0 to host node0 left intact
```

So the reference to node0 seems to work.

**Comment by kwix** [comment]
Could you try using the ip directly (`172.18.0.6`) instead of `node0` and see if that works?

**Comment by ArvsIndrarys** [comment]
> Could you try using the ip directly (`172.18.0.6`) instead of `node0` and see if that works?

I still have the error

**Comment by kwix** [comment]
Just noticed you're not setting the correct volume for the memento container.

It should be 
```
- .volumes/memento:/config
```

You're passing it the explorer config instead, which is a different thing.
```
- ./explorer/config.json:/config/config.json
```

That directory should contain the `memento.yml` file from your gist. Unless specified explicitly via the `--config` flag, Memento will search for a file named `config.yml` in that directory -- that means `memento.yml` will not work.

**Comment by ArvsIndrarys** [comment]
Okay it works, sorry for the inconvenience ^^'

Do I close the issue or let you close it?

**Comment by kwix** [comment]
Glad I could help! If you've got other problems, feel free to open another issue. I will close this one for now. 

Thank you for using Memento! <3

**Comment by SalahAdDin** [comment]
I have the same freaking problem with ganache.
