### ISSUE TITLE
Database doesn't update latest block

### ISSUE THREAD

**Issue by gperezalba** [Alethio/memento#8]
Hi,

I have a Lite-Blockexplorer with Memento running for a PoA. When I launch it, it starts the backfilling process but the Latest block in DB remains the same as when I launch and doesn't update. The blockexplorer checks the API (http://IP:PORT/api/explorer/block/latest) but DB has always the same latest block. 

My config is:
- poll-interval: "5s"
- backfill: enabled: true
- lag: enabled: false
- (everything else as default)

What could be the reason?

Thanks in advance

Guillermo

**Comment by kwix** [comment]
Hey @gperezalba ! 

This was a small bug we had. 
I just released version 1.1.3 addressing your issue. 

Let me know if that fixes it for you.

**Comment by gperezalba** [comment]
Hi @kwix 

It's working now!

Thanks
